FUNCTION(BUILD_EXECUTABLE)

    SET(oneValueArgs PROJECT_NAME FOLDER_NAME)
    SET(multiValueArgs DEPENDENCIES_LIST LINK_LIBRARIES_LIST SRC_LIST)
    CMAKE_PARSE_ARGUMENTS(BUILD "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    FILE(GLOB_RECURSE PLUGIN_SRC *.h *.hpp *.cpp *.cc *.c)
    LIST(APPEND PLUGIN_SRC ${BUILD_SRC_LIST})

    ADD_EXECUTABLE(${BUILD_PROJECT_NAME} ${PLUGIN_SRC})

    FOREACH(DEP ${BUILD_DEPENDENCIES_LIST})
        ADD_DEPENDENCIES(${BUILD_PROJECT_NAME} ${DEP})
    ENDFOREACH(DEP)

    SET_TARGET_PROPERTIES(${BUILD_PROJECT_NAME} PROPERTIES PREFIX "")
    SET_TARGET_PROPERTIES(${BUILD_PROJECT_NAME} PROPERTIES
        FOLDER ${BUILD_FOLDER_NAME}
        ARCHIVE_OUTPUT_DIRECTORY ${BUILDS_DIR}
        RUNTIME_OUTPUT_DIRECTORY ${BUILDS_DIR}
        LIBRARY_OUTPUT_DIRECTORY ${BUILDS_DIR})

    FOREACH(LIB ${BUILD_LINK_LIBRARIES_LIST})
        TARGET_LINK_LIBRARIES(${BUILD_PROJECT_NAME} ${LIB})
    ENDFOREACH(LIB)

ENDFUNCTION(BUILD_EXECUTABLE)

FUNCTION(BUILD_STATIC_LIB)

    SET(oneValueArgs PROJECT_NAME FOLDER_NAME)
    SET(multiValueArgs DEPENDENCIES_LIST LINK_LIBRARIES_LIST)
    CMAKE_PARSE_ARGUMENTS(BUILD "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    FILE(GLOB_RECURSE PLUGIN_SRC *.h *.hpp *.cpp *.cc *.c)

    ADD_LIBRARY(${BUILD_PROJECT_NAME} STATIC ${PLUGIN_SRC})

    FOREACH(DEP ${BUILD_DEPENDENCIES_LIST})
        ADD_DEPENDENCIES(${BUILD_PROJECT_NAME} ${DEP})
    ENDFOREACH(DEP)

    SET_TARGET_PROPERTIES(${BUILD_PROJECT_NAME} PROPERTIES PREFIX "")
    SET_TARGET_PROPERTIES(${BUILD_PROJECT_NAME} PROPERTIES
        FOLDER ${BUILD_FOLDER_NAME}
        ARCHIVE_OUTPUT_DIRECTORY ${BUILDS_DIR}
        RUNTIME_OUTPUT_DIRECTORY ${BUILDS_DIR}
        LIBRARY_OUTPUT_DIRECTORY ${BUILDS_DIR})

    FOREACH(LIB ${BUILD_LINK_LIBRARIES_LIST})
        TARGET_LINK_LIBRARIES(${BUILD_PROJECT_NAME} ${LIB})
    ENDFOREACH(LIB)

ENDFUNCTION(BUILD_STATIC_LIB)